---
application:
  name: "klm-background"
  project: "klm background"
  organization: "QoveryCommunity"
routers:
- name: "main-klm-background"
  routes:
  - application_name: "klm-background"
    paths:
    - "/*"
